[project]
name = "ird-manuscript"
version = "1.0"
description = ""
authors = [
    {name = "Ethan",email = "ethan.g.pierce@dartmouth.edu"}
]
license = {text = "GPL v3"}
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "jax (>=0.6.2,<0.7.0)",
    "equinox (>=0.13.0,<0.14.0)",
    "optimistix (>=0.0.10,<0.0.11)",
    "lineax (>=0.0.8,<0.0.9)",
    "jaxtyping (>=0.3.2,<0.4.0)",
    "pandas (>=2.3.1,<3.0.0)",
    "geopandas (>=1.1.1,<2.0.0)",
    "shapely (>=2.1.1,<3.0.0)",
    "rasterio (>=1.4.3,<2.0.0)",
    "xarray (>=2025.7.1,<2026.0.0)",
    "rioxarray (>=0.19.0,<0.20.0)",
    "scipy (>=1.16.0,<2.0.0)",
    "statsmodels (>=0.14.5,<0.15.0)",
    "matplotlib (>=3.10.3,<4.0.0)",
    "seaborn (>=0.13.2,<0.14.0)",
    "cmcrameri (>=1.9,<2.0)",
    "landlab (>=2.10.1)",
    "scikit-learn (>=1.7.0,<2.0.0)",
    "toml (>=0.10.2,<0.11.0)",
    "tomli (>=2.2.1,<3.0.0)",
    "pip (>=25.2,<26.0)"
]

[tool.poetry]
package-mode = false
packages = [
    {include = "ird_model", from = "./ird_model"}
]

[tool.poetry.dependencies]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
